"""Add classes field to projects

Revision ID: fa809265b83e
Revises: 
Create Date: 2025-11-12 11:53:14.008431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa809265b83e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('projects', sa.Column('classes', sa.JSON(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE projects SET classes = '[]' WHERE classes IS NULL")

    # Now make it not nullable
    op.alter_column('projects', 'classes', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'classes')
    # ### end Alembic commands ###
